# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('description', models.CharField(default='', max_length=100)),
                ('key', models.SlugField(max_length=10, unique=True)),
                ('date_created', models.DateTimeField()),
                ('date_last_view', models.DateTimeField()),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('user', models.CharField(default='anonymous', max_length=20, unique=True)),
            ],
        ),
    ]
