# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
