# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_sharing', '0003_auto_20160928_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='user',
            field=models.CharField(default='anonymous', max_length=20),
        ),
    ]
