# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_sharing', '0004_auto_20160929_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to=''),
        ),
    ]
