# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture_sharing', '0005_auto_20160930_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='picture_sharing.Picture')),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='likes_count',
        ),
        migrations.AlterField(
            model_name='picture',
            name='date_last_view',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
